[profile.default]
src = 'src'
out = 'out'
libs = ['lib', "dependencies"]
remappings = [
    '@zetachain/toolkit/=lib/toolkit/contracts/',
    '@zetachain/protocol-contracts/=lib/protocol-contracts/contracts/'
]

[dependencies]
